version: "3.8"
services:
  ml-showcase-marketbasket:
    image: ml-showcase-marketbasket
    ports:
      - "11008:8501"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s